/**
 * Maps TIX.id city names to standard Indonesian Province names matching `indonesia-provinces.json` (34 Provinces)
 */
export const CITY_TO_PROVINCE: Record<string, string> = {
  // Sumatera
  "BANDA ACEH": "DI. ACEH",
  MEDAN: "SUMATERA UTARA",
  BINJAI: "SUMATERA UTARA",
  KISARAN: "SUMATERA UTARA",
  "PEMATANG SIANTAR": "SUMATERA UTARA",
  "RANTAU PRAPAT": "SUMATERA UTARA",
  PADANG: "SUMATERA BARAT",
  PEKANBARU: "RIAU",
  DUMAI: "RIAU",
  DURI: "RIAU",
  "ROKAN HILIR": "RIAU",
  BATAM: "RIAU", // Technically Kepri, but might be grouped in 34-prov version
  "TANJUNG PINANG": "RIAU", // Technically Kepri
  JAMBI: "JAMBI",
  PALEMBANG: "SUMATERA SELATAN",
  LUBUKLINGGAU: "SUMATERA SELATAN",
  PRABUMULIH: "SUMATERA SELATAN",
  BENGKULU: "BENGKULU",
  LAMPUNG: "LAMPUNG",
  "PANGKAL PINANG": "BANGKA BELITUNG",

  // Jawa
  JAKARTA: "DKI JAKARTA",
  SERANG: "PROBANTEN",
  CILEGON: "PROBANTEN",
  TANGERANG: "PROBANTEN",
  BANDUNG: "JAWA BARAT",
  BEKASI: "JAWA BARAT",
  BOGOR: "JAWA BARAT",
  CIANJUR: "JAWA BARAT",
  CIKARANG: "JAWA BARAT",
  CIREBON: "JAWA BARAT",
  DEPOK: "JAWA BARAT",
  GARUT: "JAWA BARAT",
  INDRAMAYU: "JAWA BARAT",
  KARAWANG: "JAWA BARAT",
  PURWAKARTA: "JAWA BARAT",
  SUMEDANG: "JAWA BARAT",
  TASIKMALAYA: "JAWA BARAT",
  SEMARANG: "JAWA TENGAH",
  KLATEN: "JAWA TENGAH",
  PEKALONGAN: "JAWA TENGAH",
  PURWOKERTO: "JAWA TENGAH",
  SOLO: "JAWA TENGAH",
  TEGAL: "JAWA TENGAH",
  YOGYAKARTA: "DAERAH ISTIMEWA YOGYAKARTA",
  SURABAYA: "JAWA TIMUR",
  BLITAR: "JAWA TIMUR",
  BONDOWOSO: "JAWA TIMUR",
  GRESIK: "JAWA TIMUR",
  JEMBER: "JAWA TIMUR",
  KEDIRI: "JAWA TIMUR",
  MADIUN: "JAWA TIMUR",
  MALANG: "JAWA TIMUR",
  MOJOKERTO: "JAWA TIMUR",
  PONOROGO: "JAWA TIMUR",
  PROBOLINGGO: "JAWA TIMUR",
  SIDOARJO: "JAWA TIMUR",

  // Bali & Nusa Tenggara
  BALI: "BALI",
  MATARAM: "NUSATENGGARA BARAT",
  KUPANG: "NUSA TENGGARA TIMUR",

  // Kalimantan
  PONTIANAK: "KALIMANTAN BARAT",
  KETAPANG: "KALIMANTAN BARAT",
  SINGKAWANG: "KALIMANTAN BARAT",
  PALANGKARAYA: "KALIMANTAN TENGAH",
  "KUALA KAPUAS": "KALIMANTAN TENGAH",
  SAMPIT: "KALIMANTAN TENGAH",
  BANJARMASIN: "KALIMANTAN SELATAN",
  BANJARBARU: "KALIMANTAN SELATAN",
  BALIKPAPAN: "KALIMANTAN TIMUR",
  BONTANG: "KALIMANTAN TIMUR",
  SAMARINDA: "KALIMANTAN TIMUR",
  TARAKAN: "KALIMANTAN TIMUR", // North Kalimantan fallback

  // Sulawesi
  MANADO: "SULAWESI UTARA",
  PALU: "SULAWESI TENGAH",
  MAKASSAR: "SULAWESI SELATAN",
  KENDARI: "SULAWESI TENGGARA",
  BAUBAU: "SULAWESI TENGGARA",
  GORONTALO: "GORONTALO",
  MAMUJU: "SULAWESI SELATAN", // West Sulawesi fallback

  // Maluku & Papua
  AMBON: "MALUKU",
  TERNATE: "MALUKU UTARA",
  JAYAPURA: "IRIAN JAYA TIMUR",
  SORONG: "IRIAN JAYA BARAT",
  MANOKWARI: "IRIAN JAYA BARAT",
  TIMIKA: "IRIAN JAYA TENGAH",
};

export function getProvinceForCity(city: string): string {
  const upperCity = city.toUpperCase().trim();
  return CITY_TO_PROVINCE[upperCity] || "UNKNOWN";
}
